Реализовал алгоритм построения таблицы подзадач для нелинейной задачи
Optimization-Methods-Project-OmSU-2024/Knapsack-problem pull request #2
Opened 2024-05-20 18:41 UTC by KuznetsLex

2024-05-25 11:41 UTC, EkaterinaDerisheva requested changes
вроде всё ок! Но напиши и закоммить, пожалуйста,  хотя бы один тест на этот алгоритм, чтобы точно быть уверенным, что всё работает так, как нужно

2024-05-31 07:58 UTC, RuslanShaikin approved these changes

2024-05-31 07:58 UTC, RuslanShaikin approved these changes

2024-05-31 07:59 UTC, RuslanShaikin approved these changes

2024-05-31 08:33 UTC, merged